## Ejercicios - Algebra

In [1]:
import numpy as np

import random

In [2]:
# Versiones
print(f"numpy=={np.__version__}")

numpy==2.1.3


### Ejercicio 1:
- Usando la librería _**random**_, genera una matriz de $4x4$ de números enteros del 1 al 100, usando bucles.
- El resultado debe ser un _**np.array()**_.

In [4]:
matriz = np.array([[1, 2, 3], [1, 2, 3]])
print(matriz)
print(matriz.shape) # se pide (4,4)
# Uso de bucles for para crear una lista en python y pasarla a array de numpy

[[1 2 3]
 [1 2 3]]
(2, 3)


In [11]:
# matriz = list()
import numpy as np
import random

matriz = []
for i in range(4):
    fila = []
    
    for j in range(4):
        # numero_aleatorio = i
        # numero_aleatorio = j
        numero_aleatorio = random.randint(1, 100)
        fila.append(numero_aleatorio)
    
    matriz.append(fila)
    
np.array(matriz)

array([[91, 13, 52, 53],
       [ 1, 61, 97, 28],
       [88, 26, 10, 94],
       [37, 49, 88, 51]])

In [18]:
np.array([[random.randint(1, 100) for j in range(4)] for i in range(4)])

array([[ 20,  14,  98,  71],
       [ 42,  51,  46,  25],
       [ 77,  54,  35, 100],
       [ 27,  23,  28,  94]])

### Ejercicio 2:

- Define una función que tome como parámetro de entrada 2 valores enteros ($m$, $n$).
- La función debe generar, usando la librería _**random**_, una matriz de $mxn$ de números enteros del 1 al 100, usando bucles.
- La función debe retornar la matriz, la matriz debe ser un _**np.array()**_.

In [ ]:
matriz = np.array([[1, 2, 3], [1, 2, 3]])
print(matriz)
print(matriz.shape) # se pide (m, n)
# Uso de bucles for para crear una lista en python y pasarla a array de numpy

In [32]:
def generar_matriz(m=4, n=4):
    matriz = []
    if m <= 0 or n <= 0:
        raise ValueError("Dimensiones incorrectas")
        #print("las dimensiones deben ser mayor de 0.")
        
    for i in range(m):
        fila = []
        for j in range(n):
            numero_aleatorio = random.randint(1, 100)
            fila.append(numero_aleatorio)
        
        matriz.append(fila)
    return np.array(matriz)
    
generar_matriz(1, 4)

array([[27, 32, 61, 77]])

In [ ]:
##############################################################################################################################