## Ejercicios - NumPy 1

In [110]:
import numpy as np

In [111]:
# Versión
print(f"numpy=={np.__version__}")

numpy==2.2.0


### Ejercicio 1:
- Crea un vector con 10 elementos pares.

In [112]:
lista = []
for i in range(20):
    if i % 2 == 0:
        lista.append(i)
        
np.array(lista)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### Ejercicio 2:
- Obten el número de dimensiones y el tamaño del vector anterior.

In [113]:
array_pares = np.array(lista)

In [114]:
array_pares.ndim

1

In [115]:
array_pares.size

10

### Ejercicio 3:
- Crea una lista con 5 números pares y otra lista con 5 números impares utilizando **list comprehension** y conviertelos en una matriz de (5, 2) dimensiones.

In [116]:
lista_pares = []
for i in range(10):
    if i % 2 == 0:
        lista_pares.append(i)

np.array(lista_pares)        
print(lista_pares)

lista_impares = []
for i in range(10):
    if i % 2 != 0:
        lista_impares.append(i)
np.array(lista_impares)          
lista_impares

[0, 2, 4, 6, 8]


[1, 3, 5, 7, 9]

In [117]:
numbers = np.concatenate((lista_pares, lista_impares))
numbers

array([0, 2, 4, 6, 8, 1, 3, 5, 7, 9])

In [118]:
matriz= numbers.reshape(5,2)
matriz

array([[0, 2],
       [4, 6],
       [8, 1],
       [3, 5],
       [7, 9]])

### Ejercicio 4:
- Obten el tipo de datos de la matriz anterior.

In [119]:
matriz.dtype

dtype('int64')

### Ejercicio 5:
- Crea una matriz de ceros de dimensión (4, 4) y remplaza los elementos de la diagonal principal por los números 5.

In [120]:
matriz0 = np.zeros((4,4), int)
matriz0

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [121]:
np.fill_diagonal(matriz0, 5)
matriz0

array([[5, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 5]])

### Ejercicio 6:
- Utiliza la función _**np.linspace()**_ para crear un vector con 10 elementos entre los números: -5 y 5.

In [122]:
linspace = np.linspace(start= -5, stop=5, num=10)
print(linspace)

[-5.         -3.88888889 -2.77777778 -1.66666667 -0.55555556  0.55555556
  1.66666667  2.77777778  3.88888889  5.        ]


### Ejercicio 7:
- Crea una matriz vacía de tamaño (3, 6) con elementos del tipo flotante.

In [123]:
matriz_float = np.empty((3, 6), dtype = "float")

print(matriz_float)

[[1.43446915e-311 5.33590898e-322 1.43594782e-311 1.43594782e-311
  1.43596902e-311 1.43594782e-311]
 [1.43594782e-311 1.43594782e-311 1.43596839e-311 1.43594782e-311
  1.43594782e-311 1.43594782e-311]
 [1.43594782e-311 1.43596847e-311 1.43594782e-311 1.43597165e-311
  0.00000000e+000 0.00000000e+000]]


### Ejercicio 8:
- Utiliza la matriz anterior para llenarla con números primos (investiga en internet una función que genere números primos e implementala).

In [124]:
def es_primo(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

In [125]:
primos = []
num = 50
while len(primos) < 18:
    if es_primo(num):
        primos.append(num)
    num += 1

In [126]:
matriz_primos= np.array(primos).reshape(3,6)
matriz_primos

array([[ 53,  59,  61,  67,  71,  73],
       [ 79,  83,  89,  97, 101, 103],
       [107, 109, 113, 127, 131, 137]])

### Ejercicio 9:
- Reemplaza los números de color azul por un 99 utilizando slicing.

$$\Large
\begin{bmatrix}
 1 &  2 &  \color{Blue}{3} &  4 \\
 5 &  \color{Blue}{6} &  7 &  \color{Blue}{8} \\
 \color{Blue}{9} & 10 & 11 & 12 \\
13 & 14 & \color{Blue}{15} & 16
\end{bmatrix}
$$

In [127]:
matriz_azul = np.arange(1,17).reshape(4,4)
matriz_azul

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [128]:
numeros_a_reemplazar = [(0, 2), (1, 1), (1, 3), (2, 0), (3,2)]
nuevo_valor = 99

In [129]:
for fila, col in numeros_a_reemplazar:
    matriz_azul[fila, col] = nuevo_valor
    
print(matriz_azul)

[[ 1  2 99  4]
 [ 5 99  7 99]
 [99 10 11 12]
 [13 14 99 16]]


### Ejercicio 10:
- Obten la primera y tercera fila de la matriz.

In [130]:
matriz_azul[[0,2]]

array([[ 1,  2, 99,  4],
       [99, 10, 11, 12]])

### Ejercico 11:
- Obten la tercera columna de la matriz.

In [131]:
matriz_azul[:, 2]

array([99,  7, 11, 99])

### Ejercicio 12:
- Obtener la segunda y tercera columna de la matriz.

In [132]:
matriz_azul[:, 1:3]

array([[ 2, 99],
       [99,  7],
       [10, 11],
       [14, 99]])

### Ejercicio 13:
- Obten una submatriz con los 4 números del centro.

In [133]:
matriz_azul

array([[ 1,  2, 99,  4],
       [ 5, 99,  7, 99],
       [99, 10, 11, 12],
       [13, 14, 99, 16]])

In [134]:
matriz_azul[1:3, 1:3]

array([[99,  7],
       [10, 11]])

### Ejercicio 14:
- Aplica la función _**np.flatten()**_ a la matriz anterior para obtener un vector.

In [135]:
vector_azul= matriz_azul.flatten()
vector_azul

array([ 1,  2, 99,  4,  5, 99,  7, 99, 99, 10, 11, 12, 13, 14, 99, 16])

### Ejercicio 15:
- Aplica el método _**.reshape()**_ al vector anterior para obtener una matriz de (1, 4) dimensiones.

In [136]:
# Como no coinciden los elementos, solo será de los primeros 4 elementos.

In [137]:
matriz4 = vector_azul[:4].reshape(1,4)
matriz4

array([[ 1,  2, 99,  4]])

### Ejercicio 16:
- Crea dos matrices de dimensión (4, 4) con números aleatorios y concatenalas verticalmente.

In [148]:
matriz_a= (np.random.randint(1,20, size = (4,4)))
matriz_b= (np.random.randint(1,20, size = (4,4)))

In [149]:
print(matriz_a)
print(matriz_b)

[[ 4 11 17  3]
 [ 8  5  8  1]
 [ 7 16 11  6]
 [14  8 11  8]]
[[ 5 16 16  1]
 [ 6  5 12  9]
 [ 2 17 17 16]
 [ 7  6 14 19]]


In [150]:
np.vstack((matriz_a, matriz_b))

array([[ 4, 11, 17,  3],
       [ 8,  5,  8,  1],
       [ 7, 16, 11,  6],
       [14,  8, 11,  8],
       [ 5, 16, 16,  1],
       [ 6,  5, 12,  9],
       [ 2, 17, 17, 16],
       [ 7,  6, 14, 19]], dtype=int32)

In [154]:
np.concatenate((matriz_a, matriz_b), axis = 0)

array([[ 4, 11, 17,  3],
       [ 8,  5,  8,  1],
       [ 7, 16, 11,  6],
       [14,  8, 11,  8],
       [ 5, 16, 16,  1],
       [ 6,  5, 12,  9],
       [ 2, 17, 17, 16],
       [ 7,  6, 14, 19]], dtype=int32)

In [138]:
################################################################################################################################